### ISSUE TITLE
大佬，今天头一次使用，报错了

### ISSUE THREAD

**Issue by abcde4631** [TkzcM/pandownload-login#14]
我运行以后它的显示是这样的，它显示的我cadence那个文件夹根本不存在，我在证书里面也没找到这个证书……
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

D:\PanDownload_v2.0.1\pdproxy>pdproxy.exe
加入TG交流群：https://t.me/pandown
给我捐赠：https://acg.uy/donate.html
项目地址：https://github.com/TkzcM/pandownload-login/

启动代理成功，请将 PanData/config.ini 中的 proxy 修改为下面显示的地址（已修改请
忽略）
Traceback (most recent call last):
  File "pdproxy.py", line 44, in <module>
  File "pdproxy.py", line 32, in start
  File "lib\site-packages\mitmproxy\proxy\config.py", line 41, in __init__
  File "lib\site-packages\mitmproxy\proxy\config.py", line 62, in configure
mitmproxy.exceptions.OptionsError: Certificate Authority parent directory does n
ot exist: C:\software\Cadence\SPB_Data
[3684] Failed to execute script pdproxy

D:\PanDownload_v2.0.1\pdproxy>

**Comment by TkzcM** [comment]
下的是我的release吗？
